In [274]:
import numpy as np
import os
import pandas as pd
from sklearn import metrics
import matplotlib.pyplot as plt

from sklearn import svm
from sklearn.model_selection import train_test_split

In [275]:
path = os.getcwd() + '/dataset/dataset.csv'
org_data = pd.read_csv(path)
## org_data.drop(org_data.index[range(200)], inplace=True)
org_data

S.NO                     Name                   Movie  Happiness  \
0       1                  Pogadhe               Deepavali       0.25   
1       2             Venam Machan                    OKOK       0.25   
2       3              Loosu Penne                Vallavan       0.25   
3       4     Unakenna venum sollu         Yennai Arindhal       1.00   
4       5              Poongatrile                   Uyire       0.25   
5       6            Kanave Kanave                   David       0.00   
6       7             Mudhal Murai                     NEP       0.25   
7       8            Aaluma Doluma                 Vedalam       1.00   
8       9               Ballelakka                  Sivaji       1.00   
9      10                Oh Maname           Ullam Ketkume       0.00   
10     11         Sambo Siva Sambo              Naadodigal       0.50   
11     12             Ennama Kannu  Thiruvilayadal Arambam       0.75   
12     13    Malligaiye Malligaiye       Ninaithen Vandhai       1.00   
13     14   Yaarendru Therigiradha             Viswaroopam       0.75   
14     15    Vidaikodu Engal Naade   Kannathil Muthamittal       0.00   
15     16           Ra Ra Sarasuku             Chandramuki       0.50   
16     17               Neruppu da                  Kabali       0.75   
17     18                Anal Mele        Vaaranam Aayiram       0.75   
18     19            Manjal Veiyil     Vettaiyadu Vilayadu       0.75   
19     20      Makka Kalangudhappa             Dharmadurai       0.75   
20     21                Ava Enna         Vaaranam Aayiram       0.25   
21     22     Kannodu Kanbadhellam                   Jeans       0.75   
22     23         Ovvoru Pookalume               Autograph       0.25   
23     24               Mannipaaya                     VTV       0.50   
24     25          Takkaru Takkaru            HipHop Album       1.00   
25     26          Udhungada Sangu                     VIP       0.25   
26     27              Adiye Ivale            Romeo Juliet       0.50   
27     28     Sevandhu Pochu Nenju                     CCV       0.50   
28     29          Kadal Rasa Naan                Mariyaan       0.75   
29     30             Aruva Meesai                   Dhool       0.75   
..    ...                      ...                     ...        ...   
170   171    Uyire Uyire Piriyadhe   Santhosh Subramaniyam       0.00   
171   172              Yedho Ondru               Lesa Lesa       0.25   
172   173              Yathe Yathe               Aadukalam       0.75   
173   174              Vizhi Moodi                    Ayan       0.75   
174   175              Kokkarakko                   Ghilli       0.75   
175   176              Nakka Mukka      Kadhalil Vilundhen       1.00   
176   177     Aadungada Enna Suthi                 Pokkiri       1.00   
177   178  Aambalaikum Pombalaikum                 Kazhugu       0.50   
178   179          Damakku Damakku                Aadhavan       0.75   
179   180   Enga Area Ulla Varadha             Pudhukottai       0.75   
180   181            Kaathadi Pole                  Mayavi       0.75   
181   182    Kannadhasan Karaikudi                 Anjadhe       0.00   
182   183            Namma Kaatula                Pattiyal       0.75   
183   184             Pottu Thaaku                   Kuthu       1.00   
184   185               Nenjukkule                   Kadal       0.75   
185   186           Nee Eppo Pulla                   Kumki       0.75   
186   187                Dang Dang     Manam Kothi Paravai       0.50   
187   188  Vaanganna Vanakkanganna               Thalaivaa       0.00   
188   189      Oodha Colour Ribbon                     VVS       0.75   
189   190            Mersalayitten                      I        0.75   
190   191        Kandangi Kandangi                   Jilla       0.75   
191   192               Paatu Onnu                   Jilla       0.75   
192   193     Koodamela Koodavechi                   Rummy     

In [276]:
mfcc_cols = ['MFCC1', 'MFCC2', 'MFCC3', 'MFCC4', 'MFCC5', 'MFCC6','MFCC7','MFCC8','MFCC9','MFCC10','MFCC11','MFCC12','MFCC13']
#'SD_SC0','SD_SC1','SD_SC2','SD_SC3','SD_SC4','SD_SC5','SD_SC6',
spectral_cols = ['Mean_SC0','Mean_SC1','Mean_SC2','Mean_SC3','Mean_SC4','Mean_SC5','Mean_SC6',
                 'Mean_Centroid','SD_Centroid','Mean_Flatness','SD_Flatness']
old_mfcc = ['NMFCC1', 'NMFCC2', 'NMFCC3', 'NMFCC4', 'NMFCC5', 'NMFCC6','NMFC7','NMFCC8','NMFCC9','NMFCC10','NMFCC11','NMFCC12','NMFCC13']

In [279]:
X = np.array(pd.DataFrame(org_data, columns=old_mfcc))
mood_values = np.array(pd.DataFrame(org_data, columns=['Happiness', 'Energy']))
y = []
for coord in mood_values:
    if coord[0] <= 0.5 and coord[1] <= 0.5:
        y.append(0)
    elif coord[0] <= 0.5 and coord[1] > 0.5:
        y.append(1)
    elif coord[0] > 0.5 and coord[1] <= 0.5:
        y.append(2)
    else:
        y.append(3)
k = [(x,y.count(x)) for x in set(y)]
k

[(0, 43), (1, 21), (2, 45), (3, 91)]

In [280]:
clf = svm.SVC(kernel='linear') # Linear Kernel
X_train, X_test, y_train, y_test = train_test_split(X, y)
#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion matrix:\n",metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.54
Confusion matrix:
 [[ 1  0  5  5]
 [ 0  0  0  7]
 [ 0  0  3  4]
 [ 0  0  2 23]]
